# This is a basic workflow to help you get started with Actions

name: GitHub Pages Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      # Getting node.js
      - name: Getting node.js
        uses: actions/setup-node@v2.4.1
        
      # Installing Dependencies
      - name: Installing Deps
        run: npm ci
      
      # Building
      - name: Building the pages
        run: npm run build && npm run export && touch ./out/.nojekyll
        
      # Deploying
      - name: Deploying
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with: 
          target_branch: gh-pages
          build_dir: out
          jekyll: false
          verbose: true
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS}}
